# Generated by Django 5.0.6 on 2026-03-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role_user_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('TECHNICIAN', 'Technician'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20),
        ),
    ]
