# Generated by Django 5.2.11 on 2026-03-01 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='phone',
        ),
        migrations.AddField(
            model_name='complaint',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='complaint',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('CARD', 'CARD'), ('CASH', 'CASH')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='payment_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='issue_category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
